import { useState } from 'react';
import dashboardData from '../data/dashboard.json';
import PageShell, { Panel, Stat } from '../components/PageShell';
import { go, loadCaseId, loadTransaction } from '../state';

export default function LLMPage() {
  const context = loadTransaction();
  const [selected, setSelected] = useState(() => {
    const caseId = loadCaseId();
    const index = dashboardData.reports.findIndex((item) => item.case === caseId);
    return index >= 0 ? index : 0;
  });
  const report = dashboardData.reports[selected] ?? dashboardData.reports[0];
  if (!report) return <PageShell title="LLM Investigator" subtitle="No current DATA 298B investigation artifacts are available." />;
  return <PageShell title="LLM Investigator" subtitle="Review a saved, validated Gemma investigation grounded in retrieved transaction, graph, and community evidence." action={<select value={selected} onChange={(e) => setSelected(Number(e.target.value))} className="h-10 rounded-xl border border-[#c9d9ea] bg-white px-3 text-sm">{dashboardData.reports.map((item, index) => <option key={item.reportId} value={index}>{item.reportId} · {item.case}</option>)}</select>}><Panel title="Case header"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label="Case ID" value={report.case} detail="Validated artifact" tone="blue" /><Stat label="Account" value={report.account || '—'} detail="Selected context" tone="purple" /><Stat label="Selected LLM" value="Gemma 4 31B" detail="AML fine-tuned model" tone="green" /><Stat label="Decision" value={report.decision} detail="Model output" tone="red" /><Stat label="Confidence" value={`${(Number(report.confidence) * 100).toFixed(0)}%`} detail="Model output" tone="orange" /></div></Panel><div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1.35fr]"><Panel title="Why this case was escalated"><div className="rounded-xl bg-[#fff7e3] p-4 text-lg font-bold text-[#b45309]">{report.riskLevel} · {report.pattern}</div><p className="mt-4 text-sm leading-6 text-[#48658a]">{report.summary}</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={() => go('transactions', context, report.account, report.case)} className="rounded-xl border border-[#c9d9ea] px-4 py-2 text-sm font-bold text-[#0877ff]">Open transaction evidence</button><button onClick={() => go('graph', context, report.account, report.case)} className="rounded-xl bg-[#0877ff] px-4 py-2 text-sm font-bold text-white">Open network</button></div></Panel><Panel title="Evidence sources"><ol className="space-y-3">{report.evidence.map((item, index) => <li key={`${item}-${index}`} className="rounded-xl border border-[#dce7f2] p-3 text-sm text-[#48658a]"><span className="mr-2 inline-grid size-6 place-items-center rounded-full bg-[#eaf3ff] text-xs font-bold text-[#0877ff]">{index + 1}</span>{item}<span className="mt-2 block text-[11px] font-bold uppercase tracking-wide text-[#607590]">Retrieved evidence</span></li>)}</ol></Panel></div><Panel title="Recommended analyst actions" className="mt-4"><div className="grid gap-3 md:grid-cols-3">{report.actions.map((item, index) => <div key={`${item}-${index}`} className="rounded-xl border border-[#dce7f2] p-4 text-sm text-[#48658a]"><span className="font-bold text-[#10b981]">{index + 1}. </span>{item}</div>)}</div><p className="mt-4 text-xs text-[#607590]">Source: saved validated DATA 298B Gemma trace. The dashboard does not start new model inference.</p></Panel></PageShell>;
}
