import dashboardData from '../data/dashboard.json';
import PageShell, { Panel, Stat } from '../components/PageShell';

const metrics = [['PR-AUC', 'pr_auc'], ['ROC-AUC', 'roc_auc'], ['Precision', 'precision'], ['Recall', 'recall'], ['F1 Score', 'f1_fraud']] as const;
const llmModels = ['Gemma', 'Qwen', 'Mistral', 'Granite', 'Claude'] as const;

export default function ModelCompPage() {
  const baseline = dashboardData.models.baseline.test;
  const graph = dashboardData.models.graphEnhanced.test;
  return <PageShell title="Model Performance Comparison" subtitle="Compare saved pipeline models and see which LLM variants have actually produced artifacts."><Panel title="XGBoost transaction models"><div className="grid gap-3 md:grid-cols-2"><ModelCard name="Baseline XGBoost" metrics={baseline} tone="blue" /><ModelCard name="Graph-enhanced XGBoost" metrics={graph} tone="purple" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-[#f4f8fc] text-[#607590]"><tr><th className="px-3 py-2">Metric</th><th className="px-3 py-2">Baseline</th><th className="px-3 py-2">Graph-enhanced</th><th className="px-3 py-2">Delta</th></tr></thead><tbody>{metrics.map(([label, key]) => { const a = Number(baseline[key]); const b = Number(graph[key]); return <tr key={key} className="border-b border-[#dce7f2]"><td className="px-3 py-2 font-semibold">{label}</td><td className="px-3 py-2">{a.toFixed(4)}</td><td className="px-3 py-2 font-semibold text-[#7c3aed]">{b.toFixed(4)}</td><td className={`px-3 py-2 font-semibold ${b >= a ? 'text-[#10b981]' : 'text-[#f0445e]'}`}>{b >= a ? '+' : ''}{(b - a).toFixed(4)}</td></tr>; })}</tbody></table></div></Panel><Panel title="LLM variant readiness" className="mt-4"><p className="mb-4 text-sm text-[#607590]">The current saved reports were generated by Claude. Gemma, Qwen, Mistral, and Granite are not present in `artifacts/llm_outputs` yet, so they are shown as pending rather than mislabeled.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{llmModels.map((name) => { const count = dashboardData.llmModelCounts[name]; return <Stat key={name} label={name} value={String(count)} detail={count ? 'saved reports' : 'not run'} tone={count ? 'green' : 'blue'} />; })}</div></Panel></PageShell>;
}

function ModelCard({ name, metrics, tone }: { name: string; metrics: typeof dashboardData.models.baseline.test; tone: 'blue' | 'purple' }) {
  const color = tone === 'purple' ? 'text-[#7c3aed]' : 'text-[#0877ff]';
  return <div className="rounded-xl border border-[#dce7f2] bg-[#f8fbff] p-4"><h3 className="font-bold">{name}</h3><p className="mt-1 text-xs text-[#607590]">Test split · threshold {metrics.threshold}</p><div className="mt-4 grid grid-cols-5 gap-2">{metricsList(metrics).map(([label, value]) => <div key={label}><p className="text-[10px] text-[#607590]">{label}</p><p className={`font-bold ${color}`}>{value}</p></div>)}</div></div>;
}

function metricsList(metrics: typeof dashboardData.models.baseline.test): [string, string][] { return [['PR-AUC', metrics.pr_auc.toFixed(3)], ['ROC-AUC', metrics.roc_auc.toFixed(3)], ['Precision', metrics.precision.toFixed(3)], ['Recall', metrics.recall.toFixed(3)], ['F1', metrics.f1_fraud.toFixed(3)]]; }
