import dashboardData from '../data/dashboard.json';
import PageShell, { Panel, Stat } from '../components/PageShell';
import { go } from '../state';

export default function OverviewPage() {
  const total = dashboardData.summary.totalTransactions;
  const fraud = dashboardData.summary.fraudTransactions;
  const legitimate = total - fraud;
  const formats = dashboardData.transactions.reduce<Record<string, number>>((acc, row) => { const key = String(row['Payment Format']); acc[key] = (acc[key] ?? 0) + (Number(row['Is Laundering']) === 1 ? 1 : 0); return acc; }, {});
  const maxFormat = Math.max(...Object.values(formats), 1);
  const baseline = dashboardData.models.baseline.test;
  const graph = dashboardData.models.graphEnhanced.test;
  const pipeline = [['XGBoost', 'Transaction risk scoring', 'transactions'], ['Graph features', 'Account and network behavior', 'graph'], ['Leiden detection', 'Community context', 'graph'], ['Gemma investigator', 'Evidence-backed case review', 'llm']] as const;
  return <PageShell title="Fraud Intelligence Overview" subtitle="Move from suspicious activity to network context and analyst review."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Total transactions" value={total.toLocaleString()} detail="Processed dataset" /><Stat label="Total accounts" value={dashboardData.summary.totalAccounts.toLocaleString()} detail="Graph feature export" tone="green" /><Stat label="Fraud transactions" value={fraud.toLocaleString()} detail="Evaluation statistic" tone="red" /><Stat label="Communities" value={dashboardData.summary.communities.toLocaleString()} detail="Leiden assignments" tone="purple" /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#bcd8f5] bg-[#eaf3ff] p-5"><div><h2 className="text-lg font-bold">Start an investigation</h2><p className="mt-1 text-sm text-[#48658a]">Review the transaction queue, then carry the same account into the network and Gemma investigation views.</p></div><button onClick={() => go('transactions')} className="rounded-xl bg-[#0877ff] px-5 py-3 text-sm font-bold text-white">Explore suspicious cases</button></div><Panel title="Detection pipeline" className="mt-4"><div className="grid gap-4 lg:grid-cols-4">{pipeline.map(([name, detail, target], index) => <button key={name} onClick={() => go(target)} className="rounded-xl border border-[#dce7f2] bg-[#f8fbff] p-4 text-left transition hover:-translate-y-0.5 hover:border-[#0877ff] hover:shadow-md"><span className="mb-4 inline-grid size-8 place-items-center rounded-full bg-[#0877ff] text-sm font-bold text-white">0{index + 1}</span><h3 className="font-bold">{name}</h3><p className="mt-2 text-xs text-[#607590]">{detail}</p><span className="mt-4 inline-block text-xs font-bold text-[#0877ff]">Open →</span></button>)}</div></Panel><div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Detection reference"><div className="grid gap-3 sm:grid-cols-2"><Stat label="Baseline PR-AUC" value={baseline.pr_auc.toFixed(3)} detail="XGBoost test split" /><Stat label="Graph PR-AUC" value={graph.pr_auc.toFixed(3)} detail="Graph-enhanced test split" tone="purple" /><Stat label="Graph recall" value={`${(graph.recall * 100).toFixed(1)}%`} detail="Reference metric" tone="green" /></div></Panel><Panel title="Analyst note"><p className="text-sm leading-6 text-[#48658a]">The browser reads frozen pipeline artifacts and live read-only Neo4j graph data when the local bridge is running. Evaluation labels are kept out of the normal analyst workflow.</p></Panel></div></PageShell>;
}
